Vagrant.configure("2") do |config|
	config.vm.define :servidor do |servidor|
		servidor.vm.box = "JuanSebastianMontoya/flask"
		servidor.vm.network :private_network, ip: "192.168.50.3"
		servidor.vm.hostname = "servidor"
	end
end